from fastapi import APIRouter, Request, Response, HTTPException
from fastapi.responses import RedirectResponse
from core.supabase import get_supabase
import json

router = APIRouter()

@router.get("/login")
def login(request: Request):
    supabase = get_supabase()
    # Replace with your actual frontend URL if deployed
    redirect_url = str(request.url_for('auth_callback'))
    
    res = supabase.auth.sign_in_with_oauth(
        {
            "provider": "google",
            "options": {"redirect_to": redirect_url}
        }
    )
    
    if res and res.url:
        response = RedirectResponse(res.url)
        # Extract the code verifier generated by Supabase during OAuth setup
        if hasattr(supabase.auth, '_storage') and hasattr(supabase.auth._storage, 'storage'):
            verifier = supabase.auth._storage.storage.get("supabase.auth.token-code-verifier")
            if verifier:
                response.set_cookie(
                    key="sb-code-verifier",
                    value=verifier,
                    httponly=True,
                    samesite="lax",
                    max_age=600 # 10 minutes
                )
        return response
    raise HTTPException(status_code=500, detail="Failed to generate OAuth URL")

@router.get("/callback")
def auth_callback(request: Request):
    code = request.query_params.get("code")
    if not code:
        return RedirectResponse("http://localhost:5173/upload?error=auth-failed-no-code")
        
    supabase = get_supabase()
    
    # Inject the code verifier back into the new supabase client instance
    verifier = request.cookies.get("sb-code-verifier")
    if verifier and hasattr(supabase.auth, '_storage') and hasattr(supabase.auth._storage, 'storage'):
        supabase.auth._storage.storage["supabase.auth.token-code-verifier"] = verifier
    
    try:
        res = supabase.auth.exchange_code_for_session({"auth_code": code})
        # Set the access token in an HTTP-only cookie
        access_token = res.session.access_token
        refresh_token = res.session.refresh_token
        
        response = RedirectResponse("http://localhost:5173/tables")
        response.set_cookie(key="sb-access-token", value=access_token, httponly=True, samesite="lax", max_age=res.session.expires_in)
        response.set_cookie(key="sb-refresh-token", value=refresh_token, httponly=True, samesite="lax", max_age=res.session.expires_in)
        return response
    except Exception as e:
        print(f"Auth error: {e}")
        return RedirectResponse("http://localhost:5173/upload?error=auth-failed")

@router.get("/session")
def get_session(request: Request):
    token = request.cookies.get("sb-access-token")
    if not token:
        return {"session": None}
        
    supabase = get_supabase()
    try:
        user = supabase.auth.get_user(token)
        if user and user.user:
            return {"session": {"user": user.user.model_dump()}}
        return {"session": None}
    except Exception:
        return {"session": None}

@router.post("/logout")
def logout(response: Response):
    response.delete_cookie("sb-access-token")
    response.delete_cookie("sb-refresh-token")
    return {"message": "Logged out successfully"}
